BEGIN;

INSERT INTO roles (id_rol, nombre_rol)
VALUES (6, 'servicios_escolares')
ON CONFLICT (id_rol) DO UPDATE SET nombre_rol = EXCLUDED.nombre_rol;

CREATE TABLE IF NOT EXISTS periodos_estadia (
  id_periodo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  clave VARCHAR(40) NOT NULL UNIQUE,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  fecha_limite_registro_empresa DATE,
  fecha_limite_seguro DATE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  instrucciones TEXT,
  creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_periodo_fechas CHECK (fecha_fin >= fecha_inicio)
);

CREATE TABLE IF NOT EXISTS guias_estadia (
  id_guia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_periodo INTEGER REFERENCES periodos_estadia(id_periodo) ON DELETE CASCADE,
  nombre VARCHAR(160) NOT NULL,
  version VARCHAR(40) NOT NULL,
  descripcion TEXT,
  ruta_archivo TEXT NOT NULL,
  mime_type VARCHAR(120),
  nombre_original VARCHAR(255),
  vigente BOOLEAN NOT NULL DEFAULT TRUE,
  publicada_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  publicada_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rubricas_estadia (
  id_rubrica INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_periodo INTEGER REFERENCES periodos_estadia(id_periodo) ON DELETE CASCADE,
  nombre VARCHAR(150) NOT NULL,
  descripcion TEXT,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  creada_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  creada_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rubrica_criterios_estadia (
  id_criterio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_rubrica INTEGER NOT NULL REFERENCES rubricas_estadia(id_rubrica) ON DELETE CASCADE,
  criterio VARCHAR(180) NOT NULL,
  descripcion TEXT,
  peso NUMERIC(5,2) NOT NULL DEFAULT 0,
  orden INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT chk_rubrica_peso CHECK (peso >= 0 AND peso <= 100)
);

CREATE TABLE IF NOT EXISTS talleres_estadia (
  id_taller INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_periodo INTEGER NOT NULL REFERENCES periodos_estadia(id_periodo) ON DELETE CASCADE,
  nombre VARCHAR(160) NOT NULL,
  descripcion TEXT,
  fecha_hora TIMESTAMP,
  modalidad VARCHAR(30) DEFAULT 'presencial',
  ubicacion VARCHAR(200),
  obligatorio BOOLEAN NOT NULL DEFAULT TRUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS grupos_estadia (
  id_grupo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_periodo INTEGER NOT NULL REFERENCES periodos_estadia(id_periodo) ON DELETE CASCADE,
  nombre VARCHAR(80) NOT NULL,
  carrera VARCHAR(150),
  id_profesor INTEGER NOT NULL REFERENCES profesores(id_profesor),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (id_periodo, nombre)
);

CREATE TABLE IF NOT EXISTS grupo_estudiantes_estadia (
  id_grupo INTEGER NOT NULL REFERENCES grupos_estadia(id_grupo) ON DELETE CASCADE,
  id_estudiante INTEGER NOT NULL REFERENCES estudiantes(id_estudiante) ON DELETE CASCADE,
  asignado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_grupo, id_estudiante)
);

CREATE TABLE IF NOT EXISTS fechas_avances_estadia (
  id_fecha_avance INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_grupo INTEGER NOT NULL REFERENCES grupos_estadia(id_grupo) ON DELETE CASCADE,
  numero_avance INTEGER NOT NULL,
  titulo VARCHAR(120) NOT NULL,
  fecha_apertura TIMESTAMP,
  fecha_limite TIMESTAMP NOT NULL,
  id_rubrica INTEGER REFERENCES rubricas_estadia(id_rubrica) ON DELETE SET NULL,
  permite_reentrega BOOLEAN NOT NULL DEFAULT TRUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (id_grupo, numero_avance),
  CONSTRAINT chk_numero_avance CHECK (numero_avance BETWEEN 1 AND 3)
);

CREATE TABLE IF NOT EXISTS estadias (
  id_estadia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_periodo INTEGER NOT NULL REFERENCES periodos_estadia(id_periodo),
  id_estudiante INTEGER NOT NULL REFERENCES estudiantes(id_estudiante),
  id_grupo INTEGER NOT NULL REFERENCES grupos_estadia(id_grupo),
  id_profesor INTEGER NOT NULL REFERENCES profesores(id_profesor),
  id_empresa INTEGER REFERENCES empresas(id_empresa) ON DELETE SET NULL,
  empresa_externa BOOLEAN NOT NULL DEFAULT FALSE,
  empresa_razon_social VARCHAR(180),
  empresa_rfc VARCHAR(20),
  empresa_giro VARCHAR(150),
  empresa_domicilio TEXT,
  empresa_ubicacion VARCHAR(180),
  empresa_telefono VARCHAR(40),
  empresa_correo VARCHAR(180),
  responsable_nombre VARCHAR(180),
  responsable_cargo VARCHAR(150),
  responsable_correo VARCHAR(180),
  responsable_telefono VARCHAR(40),
  proyecto_titulo VARCHAR(200) NOT NULL,
  proyecto_area VARCHAR(160),
  proyecto_problematica TEXT,
  proyecto_objetivo_general TEXT,
  proyecto_objetivos_especificos TEXT,
  proyecto_justificacion TEXT,
  proyecto_alcance TEXT,
  proyecto_actividades TEXT,
  proyecto_entregables TEXT,
  proyecto_tecnologias TEXT,
  fecha_inicio DATE,
  fecha_fin DATE,
  estado VARCHAR(40) NOT NULL DEFAULT 'registro_inicial',
  creada_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizada_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (id_periodo, id_estudiante)
);

CREATE TABLE IF NOT EXISTS expedientes_estadia (
  id_expediente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estadia INTEGER NOT NULL UNIQUE REFERENCES estadias(id_estadia) ON DELETE CASCADE,
  folio VARCHAR(60) NOT NULL UNIQUE,
  estado VARCHAR(40) NOT NULL DEFAULT 'incompleto',
  porcentaje_completo INTEGER NOT NULL DEFAULT 0,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_expediente_porcentaje CHECK (porcentaje_completo BETWEEN 0 AND 100)
);

CREATE TABLE IF NOT EXISTS seguros_facultativos (
  id_seguro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estadia INTEGER NOT NULL UNIQUE REFERENCES estadias(id_estadia) ON DELETE CASCADE,
  numero_seguro VARCHAR(80),
  folio_pago VARCHAR(100),
  fecha_pago DATE,
  vigencia_inicio DATE,
  vigencia_fin DATE,
  monto NUMERIC(12,2),
  ruta_comprobante TEXT,
  mime_type VARCHAR(120),
  nombre_original VARCHAR(255),
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
  observaciones TEXT,
  validado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  validado_en TIMESTAMP,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_seguro_estado CHECK (estado IN ('pendiente','en_revision','validado','requiere_correccion','rechazado'))
);

CREATE TABLE IF NOT EXISTS entregas_avances_estadia (
  id_entrega INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estadia INTEGER NOT NULL REFERENCES estadias(id_estadia) ON DELETE CASCADE,
  id_fecha_avance INTEGER NOT NULL REFERENCES fechas_avances_estadia(id_fecha_avance) ON DELETE CASCADE,
  version INTEGER NOT NULL DEFAULT 1,
  ruta_archivo TEXT NOT NULL,
  mime_type VARCHAR(120),
  nombre_original VARCHAR(255),
  comentario_estudiante TEXT,
  entregado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado VARCHAR(30) NOT NULL DEFAULT 'entregado',
  es_tardia BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE (id_estadia, id_fecha_avance, version),
  CONSTRAINT chk_entrega_estado CHECK (estado IN ('entregado','en_revision','requiere_correccion','aprobado'))
);

CREATE TABLE IF NOT EXISTS revisiones_avances_estadia (
  id_revision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_entrega INTEGER NOT NULL REFERENCES entregas_avances_estadia(id_entrega) ON DELETE CASCADE,
  id_profesor INTEGER NOT NULL REFERENCES profesores(id_profesor),
  nivel VARCHAR(2) NOT NULL,
  calificacion INTEGER NOT NULL,
  observaciones TEXT,
  requiere_correccion BOOLEAN NOT NULL DEFAULT FALSE,
  revisado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_revision_nivel CHECK (nivel IN ('SA','DE','AU')),
  CONSTRAINT chk_revision_calificacion CHECK ((nivel='SA' AND calificacion=8) OR (nivel='DE' AND calificacion=9) OR (nivel='AU' AND calificacion=10))
);

CREATE INDEX IF NOT EXISTS idx_estadias_estudiante ON estadias(id_estudiante);
CREATE INDEX IF NOT EXISTS idx_estadias_profesor ON estadias(id_profesor);
CREATE INDEX IF NOT EXISTS idx_estadias_grupo ON estadias(id_grupo);
CREATE INDEX IF NOT EXISTS idx_seguros_estado ON seguros_facultativos(estado);
CREATE INDEX IF NOT EXISTS idx_entregas_estadia ON entregas_avances_estadia(id_estadia);

COMMIT;

SELECT 'Migracion 13 aplicada. Modulo integral de estadias V5 listo.' AS resultado;
