BEGIN;

-- SkillMatch V6: grupos escolares, tutores, talleres/entregas, calificaciones configurables y memoria final.

CREATE TABLE IF NOT EXISTS grupos_escolares (
  id_grupo_escolar INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  id_carrera INTEGER NOT NULL REFERENCES carreras(id_carrera),
  generacion VARCHAR(80),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(nombre, id_carrera, generacion)
);

ALTER TABLE estudiantes ADD COLUMN IF NOT EXISTS id_grupo_escolar INTEGER REFERENCES grupos_escolares(id_grupo_escolar) ON DELETE SET NULL;
ALTER TABLE profesores ADD COLUMN IF NOT EXISTS id_carrera INTEGER REFERENCES carreras(id_carrera) ON DELETE SET NULL;
ALTER TABLE profesores ADD COLUMN IF NOT EXISTS tutor_estadia BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE grupos_estadia ADD COLUMN IF NOT EXISTS id_carrera INTEGER REFERENCES carreras(id_carrera) ON DELETE SET NULL;
ALTER TABLE grupos_estadia ADD COLUMN IF NOT EXISTS generacion VARCHAR(80);
ALTER TABLE grupos_estadia ADD COLUMN IF NOT EXISTS max_alumnos INTEGER NOT NULL DEFAULT 6;

CREATE TABLE IF NOT EXISTS periodo_grupos_escolares (
  id_periodo INTEGER NOT NULL REFERENCES periodos_estadia(id_periodo) ON DELETE CASCADE,
  id_grupo_escolar INTEGER NOT NULL REFERENCES grupos_escolares(id_grupo_escolar) ON DELETE CASCADE,
  seleccionado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id_periodo, id_grupo_escolar)
);

ALTER TABLE talleres_estadia ADD COLUMN IF NOT EXISTS fecha_apertura TIMESTAMP;
ALTER TABLE talleres_estadia ADD COLUMN IF NOT EXISTS fecha_cierre TIMESTAMP;
ALTER TABLE talleres_estadia ADD COLUMN IF NOT EXISTS numero_entrega INTEGER;
ALTER TABLE talleres_estadia ADD COLUMN IF NOT EXISTS id_rubrica INTEGER REFERENCES rubricas_estadia(id_rubrica) ON DELETE SET NULL;

-- En V6 cada taller equivale a una entrega. Se mantiene fechas_avances_estadia por compatibilidad.
ALTER TABLE entregas_avances_estadia ALTER COLUMN ruta_archivo DROP NOT NULL;
ALTER TABLE entregas_avances_estadia ADD COLUMN IF NOT EXISTS enlace_google_docs TEXT;
ALTER TABLE entregas_avances_estadia ADD COLUMN IF NOT EXISTS comentario_actualizado_en TIMESTAMP;

ALTER TABLE estadias ADD COLUMN IF NOT EXISTS memoria_final_ruta TEXT;
ALTER TABLE estadias ADD COLUMN IF NOT EXISTS memoria_final_nombre VARCHAR(255);
ALTER TABLE estadias ADD COLUMN IF NOT EXISTS memoria_final_mime VARCHAR(120);
ALTER TABLE estadias ADD COLUMN IF NOT EXISTS memoria_final_subida_en TIMESTAMP;
ALTER TABLE estadias ADD COLUMN IF NOT EXISTS memoria_final_habilitada BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE estadias ADD COLUMN IF NOT EXISTS memoria_final_autorizada BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE estadias ADD COLUMN IF NOT EXISTS memoria_final_autorizada_por INTEGER REFERENCES profesores(id_profesor) ON DELETE SET NULL;
ALTER TABLE estadias ADD COLUMN IF NOT EXISTS memoria_final_autorizada_en TIMESTAMP;
ALTER TABLE estadias ADD COLUMN IF NOT EXISTS horario_laboral TEXT;

CREATE TABLE IF NOT EXISTS configuracion_calificaciones_estadia (
  id_config INTEGER PRIMARY KEY DEFAULT 1,
  valor_sa NUMERIC(5,2) NOT NULL DEFAULT 8,
  valor_de NUMERIC(5,2) NOT NULL DEFAULT 9,
  valor_au NUMERIC(5,2) NOT NULL DEFAULT 10,
  actualizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unica_config CHECK (id_config = 1)
);
INSERT INTO configuracion_calificaciones_estadia(id_config) VALUES (1) ON CONFLICT(id_config) DO NOTHING;

-- V6 permite valores institucionales configurables, por eso se eliminan restricciones rígidas de V5.
ALTER TABLE revisiones_avances_estadia DROP CONSTRAINT IF EXISTS chk_revision_calificacion;
ALTER TABLE revisiones_avances_estadia ALTER COLUMN calificacion TYPE NUMERIC(5,2) USING calificacion::numeric;

CREATE INDEX IF NOT EXISTS idx_estudiantes_grupo_escolar ON estudiantes(id_grupo_escolar);
CREATE INDEX IF NOT EXISTS idx_profesores_tutor_estadia ON profesores(tutor_estadia);
CREATE INDEX IF NOT EXISTS idx_grupos_escolares_carrera ON grupos_escolares(id_carrera);

COMMIT;

SELECT 'Migracion 14 aplicada. SkillMatch V6 listo.' AS resultado;
