-- =============================================================
-- SKILLMATCH V7 - Evaluacion por criterios, empresa y seguimiento
-- Ejecutar DESPUES de 15_estadias_v6_1.sql
-- PostgreSQL
-- =============================================================
BEGIN;

-- La V5 restringía nivel a SA/DE/AU y fijaba sus calificaciones. V7 migra
-- a una escala institucional configurable (NA/CO/CD/CA) manteniendo
-- compatibilidad con datos históricos.
ALTER TABLE revisiones_avances_estadia DROP CONSTRAINT IF EXISTS chk_revision_nivel;
ALTER TABLE revisiones_avances_estadia DROP CONSTRAINT IF EXISTS chk_revision_calificacion;
ALTER TABLE revisiones_avances_estadia ALTER COLUMN calificacion TYPE NUMERIC(5,2) USING calificacion::NUMERIC(5,2);
ALTER TABLE revisiones_avances_estadia
  ADD CONSTRAINT chk_revision_nivel_v7 CHECK (nivel IN ('SA','DE','AU','NA','CO','CD','CA'));
ALTER TABLE revisiones_avances_estadia
  ADD CONSTRAINT chk_revision_calificacion_v7 CHECK (calificacion >= 0 AND calificacion <= 10);

-- Escala institucional configurable. La fotografía de referencia de la UTEQ
-- usa NA / CO / CD / CA. Se mantiene en tabla para poder modificarla sin código.
CREATE TABLE IF NOT EXISTS niveles_evaluacion_estadia (
  codigo VARCHAR(10) PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  valor NUMERIC(5,2),
  orden INTEGER NOT NULL DEFAULT 1,
  aprobado BOOLEAN NOT NULL DEFAULT TRUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO niveles_evaluacion_estadia (codigo,nombre,valor,orden,aprobado,activo) VALUES
('NA','No acreditado',0,1,FALSE,TRUE),
('CO','Competente',8,2,TRUE,TRUE),
('CD','Competente destacado',9,3,TRUE,TRUE),
('CA','Competente autónomo',10,4,TRUE,TRUE)
ON CONFLICT (codigo) DO UPDATE SET
  nombre=EXCLUDED.nombre, valor=EXCLUDED.valor, orden=EXCLUDED.orden,
  aprobado=EXCLUDED.aprobado, activo=EXCLUDED.activo;

-- Criterios universales de cada taller/entrega.
CREATE TABLE IF NOT EXISTS criterios_taller_estadia (
  id_criterio_taller INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_taller INTEGER NOT NULL CHECK (numero_taller BETWEEN 1 AND 3),
  criterio VARCHAR(180) NOT NULL,
  orden INTEGER NOT NULL DEFAULT 1,
  peso NUMERIC(5,2) NOT NULL DEFAULT 25 CHECK (peso > 0 AND peso <= 100),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE(numero_taller, criterio)
);

INSERT INTO criterios_taller_estadia (numero_taller,criterio,orden,peso) VALUES
(1,'Resumen + Abstract',1,25),(1,'Definición del problema',2,25),(1,'Justificación',3,25),(1,'Objetivos',4,25),
(2,'Entregables',1,25),(2,'Recursos utilizados',2,25),(2,'Cronograma',3,25),(2,'Desarrollo del proyecto',4,25),
(3,'Análisis de resultados',1,25),(3,'Conclusiones',2,25),(3,'Referencias',3,25),(3,'Apéndice',4,25)
ON CONFLICT (numero_taller,criterio) DO UPDATE SET orden=EXCLUDED.orden,peso=EXCLUDED.peso,activo=TRUE;

-- Evaluación de cada criterio de una entrega por el profesor.
CREATE TABLE IF NOT EXISTS evaluaciones_criterios_taller (
  id_evaluacion_criterio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_entrega INTEGER NOT NULL REFERENCES entregas_avances_estadia(id_entrega) ON DELETE CASCADE,
  id_criterio_taller INTEGER NOT NULL REFERENCES criterios_taller_estadia(id_criterio_taller),
  id_profesor INTEGER NOT NULL REFERENCES profesores(id_profesor),
  codigo_nivel VARCHAR(10) NOT NULL REFERENCES niveles_evaluacion_estadia(codigo),
  valor NUMERIC(5,2) NOT NULL,
  entregado BOOLEAN NOT NULL DEFAULT TRUE,
  completo BOOLEAN NOT NULL DEFAULT FALSE,
  observacion TEXT,
  evaluado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(id_entrega,id_criterio_taller)
);

-- Preguntas institucionales para evaluación de la empresa. Son editables.
CREATE TABLE IF NOT EXISTS preguntas_evaluacion_empresa (
  id_pregunta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria VARCHAR(30) NOT NULL CHECK (categoria IN ('desempeno','actitud')),
  pregunta TEXT NOT NULL,
  orden INTEGER NOT NULL,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE(orden)
);

INSERT INTO preguntas_evaluacion_empresa(categoria,pregunta,orden) VALUES
('desempeno','Cumple las actividades y responsabilidades asignadas.',1),
('desempeno','Entrega su trabajo con la calidad esperada.',2),
('desempeno','Cumple los tiempos y compromisos acordados.',3),
('desempeno','Aplica adecuadamente sus conocimientos técnicos en el trabajo.',4),
('desempeno','Analiza problemas y propone soluciones pertinentes.',5),
('actitud','Muestra puntualidad, responsabilidad y disciplina.',6),
('actitud','Se integra y colabora adecuadamente con el equipo de trabajo.',7),
('actitud','Mantiene una comunicación clara y profesional.',8),
('actitud','Muestra iniciativa, disposición para aprender y mejorar.',9),
('actitud','Mantiene una actitud respetuosa, ética y profesional.',10)
ON CONFLICT (orden) DO UPDATE SET categoria=EXCLUDED.categoria,pregunta=EXCLUDED.pregunta,activa=TRUE;

-- Dos evaluaciones por estadía: inicial y final. El token permite responder sin cuenta.
CREATE TABLE IF NOT EXISTS evaluaciones_empresa_estadia (
  id_evaluacion_empresa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estadia INTEGER NOT NULL REFERENCES estadias(id_estadia) ON DELETE CASCADE,
  momento VARCHAR(20) NOT NULL CHECK (momento IN ('inicial','final')),
  token_publico VARCHAR(80) NOT NULL UNIQUE,
  generada_por INTEGER NOT NULL REFERENCES profesores(id_profesor),
  generada_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  vence_en TIMESTAMP,
  respondida_en TIMESTAMP,
  evaluador_nombre VARCHAR(180),
  evaluador_correo VARCHAR(180),
  evaluador_cargo VARCHAR(150),
  promedio NUMERIC(5,2),
  codigo_final VARCHAR(10) REFERENCES niveles_evaluacion_estadia(codigo),
  observaciones TEXT,
  UNIQUE(id_estadia,momento)
);

CREATE TABLE IF NOT EXISTS respuestas_evaluacion_empresa (
  id_respuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_evaluacion_empresa INTEGER NOT NULL REFERENCES evaluaciones_empresa_estadia(id_evaluacion_empresa) ON DELETE CASCADE,
  id_pregunta INTEGER NOT NULL REFERENCES preguntas_evaluacion_empresa(id_pregunta),
  codigo_nivel VARCHAR(10) NOT NULL REFERENCES niveles_evaluacion_estadia(codigo),
  valor NUMERIC(5,2) NOT NULL,
  comentario TEXT,
  UNIQUE(id_evaluacion_empresa,id_pregunta)
);

-- Seguimiento formal de estadía.
CREATE TABLE IF NOT EXISTS seguimientos_estadia (
  id_seguimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estadia INTEGER NOT NULL REFERENCES estadias(id_estadia) ON DELETE CASCADE,
  registrado_por INTEGER NOT NULL REFERENCES usuarios(id_usuario),
  tipo VARCHAR(30) NOT NULL DEFAULT 'seguimiento'
    CHECK (tipo IN ('inicio','seguimiento','incidencia','reunion','acuerdo','cierre')),
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  resumen TEXT NOT NULL,
  acuerdos TEXT,
  proxima_revision DATE,
  estado VARCHAR(20) NOT NULL DEFAULT 'abierto' CHECK (estado IN ('abierto','cerrado')),
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Documentos que forman parte del expediente digital.
CREATE TABLE IF NOT EXISTS documentos_expediente_estadia (
  id_documento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estadia INTEGER NOT NULL REFERENCES estadias(id_estadia) ON DELETE CASCADE,
  tipo VARCHAR(50) NOT NULL,
  nombre VARCHAR(180) NOT NULL,
  ruta_archivo TEXT,
  enlace TEXT,
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente','en_revision','validado','rechazado','no_aplica')),
  obligatorio BOOLEAN NOT NULL DEFAULT TRUE,
  observaciones TEXT,
  cargado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  validado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  cargado_en TIMESTAMP,
  validado_en TIMESTAMP,
  UNIQUE(id_estadia,tipo)
);

-- Inicio formal: conserva fecha real y autorización institucional sin duplicar datos del proyecto.
CREATE TABLE IF NOT EXISTS inicio_formal_estadia (
  id_inicio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estadia INTEGER NOT NULL UNIQUE REFERENCES estadias(id_estadia) ON DELETE CASCADE,
  fecha_inicio_real DATE,
  autorizado BOOLEAN NOT NULL DEFAULT FALSE,
  autorizado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  autorizado_en TIMESTAMP,
  observaciones TEXT,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_eval_criterio_entrega ON evaluaciones_criterios_taller(id_entrega);
CREATE INDEX IF NOT EXISTS idx_eval_empresa_estadia ON evaluaciones_empresa_estadia(id_estadia,momento);
CREATE INDEX IF NOT EXISTS idx_seguimientos_estadia_fecha ON seguimientos_estadia(id_estadia,fecha DESC);
CREATE INDEX IF NOT EXISTS idx_documentos_expediente ON documentos_expediente_estadia(id_estadia,estado);

COMMIT;

SELECT 'Migracion 16 aplicada. SkillMatch V7 evaluaciones y seguimiento listo.' AS resultado;
