const express = require('express');
const router = express.Router();
const verificarToken = require('../middlewares/authMiddleware');
const controller = require('../controllers/estadiaController');
const { uploadEvidencias, procesarYSubirACloudinary } = require('../middlewares/uploadEvidencias');

router.use(verificarToken);
router.get('/resumen', controller.resumen);
router.get('/periodos', controller.listarPeriodos);
router.post('/periodos', controller.crearPeriodo);
router.get('/guias', controller.listarGuias);
router.post('/guias', uploadEvidencias.single('archivo'), procesarYSubirACloudinary, controller.crearGuia);
router.get('/rubricas', controller.listarRubricas);
router.get('/talleres', controller.listarTalleres);
router.post('/talleres', controller.crearTaller);
router.post('/rubricas', controller.crearRubrica);
router.get('/grupos', controller.listarGrupos);
router.post('/grupos', controller.crearGrupo);
router.post('/grupos/:id/alumnos', controller.asignarAlumnoGrupo);
router.get('/grupos/:id/alumnos', controller.alumnosGrupo);
router.get('/grupos/:id/fechas', controller.fechasGrupo);
router.put('/grupos/:id/fechas', controller.guardarFechasGrupo);
router.get('/catalogos-admin', controller.catalogosAdmin);
router.get('/registro/contexto', controller.miContextoRegistro);
router.get('/mi-estadia', controller.obtenerMiEstadia);
router.post('/mi-estadia', controller.registrarMiEstadia);
router.post('/mi-estadia/seguro', uploadEvidencias.single('archivo'), procesarYSubirACloudinary, controller.guardarSeguro);
router.get('/seguros', controller.listarSeguros);
router.put('/seguros/:id', controller.validarSeguro);
router.post('/avances/:idFecha/entregas', uploadEvidencias.single('archivo'), procesarYSubirACloudinary, controller.entregarAvance);
router.get('/profesor/entregas', controller.entregasProfesor);
router.post('/profesor/entregas/:id/revision', controller.revisarEntrega);
router.get('/expedientes', controller.listarExpedientes);
router.get('/expedientes/:id', controller.detalleExpediente);


router.put('/periodos/:id', controller.actualizarPeriodo);
router.get('/catalogos-v6', controller.catalogosV6);
router.post('/grupos-escolares', controller.crearGrupoEscolar);
router.put('/alumnos/:id/escolar', controller.actualizarAlumnoEscolar);
router.put('/profesores/:id/tutor', controller.actualizarProfesorTutor);
router.put('/grupos/:id/tutor', controller.actualizarTutorGrupo);
router.get('/periodos/:id/grupos-escolares', controller.obtenerGruposPeriodo);
router.put('/periodos/:id/grupos-escolares', controller.guardarGruposPeriodo);
router.post('/periodos/:id/generar-grupos', controller.generarGruposEstadia);
router.put('/talleres/:id', controller.actualizarTaller);
router.get('/configuracion-calificaciones', controller.obtenerCalificaciones);
router.put('/configuracion-calificaciones', controller.actualizarCalificaciones);
router.get('/servicios/alumnos', controller.alumnosServicios);
router.get('/servicios/alumnos/:id', controller.detalleAlumnoServicios);
router.get('/profesor/grupos', controller.gruposProfesor);
router.get('/profesor/grupos/:id', controller.detalleGrupoProfesor);
router.post('/avances/:idFecha/enlace', controller.entregarEnlace);
router.post('/mi-estadia/memoria-final', uploadEvidencias.single('archivo'), procesarYSubirACloudinary, controller.subirMemoriaFinal);
router.put('/profesor/estadias/:idEstadia/memoria-final', controller.autorizarMemoriaFinal);

module.exports = router;
